import { writeFileSync } from 'fs';
import { promisify } from 'util';
import * as dedent from 'dedent';
import * as child from 'child_process';

const exec = promisify(child.exec);

// Inspired by Vilmantas Baranauskas, https://stackoverflow.com/a/42199863/587091
async function createVersionsFile(filename: string) {
  const revision = (await exec('git rev-parse --short HEAD')).stdout
    .toString()
    .trim();
  console.log(`revision: '${revision}'`);

  const content = dedent`
      // this file is automatically generated by git.version.ts script
      export const versions = {
        revision: '${revision}',
      };`;

  writeFileSync(filename, content, { encoding: 'utf8' });
}

createVersionsFile('src/environments/versions.prod.ts');
