#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Generating license report"
npx license-report --config license-report-config.json > src/assets/license-report.json && git add src/assets/license-report.json
npx lint-staged
