/**
 * A DXCC entity. Entities are countries and other regions defined by the ARRL.
 */
export class DxccEntity {
  id: number;
  name: string;
  continent: string;
  prefixRegex?: RegExp;
  flag: string;
}

/**
 * DXCC reference utility for retrieving DXCC information.
 *
 * Based on https://github.com/k0swe/dxcc-json.
 *
 * ```
 * $ < dxcc.json jq '{dxcc: [ .dxcc[] | select( .deleted==false ) |
 *     {id: .entityCode, name: .name, continent: .continent[0],
 *     prefixRegex: .prefixRegex, flag: .flag} ]}'
 * ```
 */
export class DxccRef {
  private static readonly dxcc: DxccEntity[] = [
    {
      id: 1,
      name: 'Canada',
      continent: 'NA',
      prefixRegex: /^V[A-GOY][A-Z0-9/]*$/,
      flag: '🇨🇦',
    },
    {
      id: 3,
      name: 'Afghanistan',
      continent: 'AS',
      prefixRegex: /^(YA|T6)[A-Z0-9/]*$/,
      flag: '🇦🇫',
    },
    {
      id: 4,
      name: 'Agaléga and Saint Brandon',
      continent: 'AF',
      prefixRegex: /^3B[67][A-Z0-9/]*$/,
      flag: '🇲🇺',
    },
    {
      id: 5,
      name: 'Åland Islands',
      continent: 'EU',
      prefixRegex: /^OH0[A-Z0-9/]*$/,
      flag: '🇦🇽',
    },
    {
      id: 6,
      name: 'Alaska',
      continent: 'NA',
      prefixRegex: /^[KANW]L[A-Z0-9/]*$/,
      flag: '🇺🇸',
    },
    {
      id: 7,
      name: 'Albania',
      continent: 'EU',
      prefixRegex: /^ZA[A-Z0-9/]*$/,
      flag: '🇦🇱',
    },
    {
      id: 9,
      name: 'American Samoa',
      continent: 'OC',
      prefixRegex: /^KH8[A-Z0-9/]*$/,
      flag: '🇦🇸',
    },
    {
      id: 10,
      name: 'Amsterdam and Saint-Paul Islands',
      continent: 'AF',
      prefixRegex: /^FT\/Z[A-Z0-9/]*$/,
      flag: '🇹🇫',
    },
    {
      id: 11,
      name: 'Andaman and Nicobar Islands',
      continent: 'AS',
      prefixRegex: /^VU4[A-Z0-9/]*$/,
      flag: '🇮🇳',
    },
    {
      id: 12,
      name: 'Anguilla',
      continent: 'NA',
      prefixRegex: /^VP2E[A-Z0-9/]*$/,
      flag: '🇦🇮',
    },
    {
      id: 13,
      name: 'Antarctica',
      continent: 'AN',
      prefixRegex: /^(CE9|KC4)[A-Z0-9/]*$/,
      flag: '🇦🇶',
    },
    {
      id: 14,
      name: 'Armenia',
      continent: 'AS',
      prefixRegex: /^EK[A-Z0-9/]*$/,
      flag: '🇦🇲',
    },
    {
      id: 15,
      name: 'Asiatic Russia',
      continent: 'AS',
      prefixRegex: /^(U[A-I][089]|R[A-Z])[A-Z0-9/]*$/,
      flag: '🇷🇺',
    },
    {
      id: 16,
      name: 'New Zealand Subantarctic Islands',
      continent: 'OC',
      prefixRegex: /^ZL9[A-Z0-9/]*$/,
      flag: '🇳🇿',
    },
    {
      id: 17,
      name: 'Isla de Aves',
      continent: 'NA',
      prefixRegex: /^YV0[A-Z0-9/]*$/,
      flag: '🇻🇪',
    },
    {
      id: 18,
      name: 'Azerbaijan',
      continent: 'AS',
      prefixRegex: /^4[JK][A-Z0-9/]*$/,
      flag: '🇦🇿',
    },
    {
      id: 20,
      name: 'Howland and Baker Islands',
      continent: 'OC',
      prefixRegex: /^KH1[A-Z0-9/]*$/,
      flag: '🇺🇲',
    },
    {
      id: 21,
      name: 'Balearic Islands',
      continent: 'EU',
      prefixRegex: /^E[A-H]6[A-Z0-9/]*$/,
      flag: '🇪🇸',
    },
    {
      id: 22,
      name: 'Palau',
      continent: 'OC',
      prefixRegex: /^T8[A-Z0-9/]*$/,
      flag: '🇵🇼',
    },
    {
      id: 24,
      name: 'Bouvet Island',
      continent: 'AF',
      prefixRegex: /^3Y[A-Z0-9/]*$/,
      flag: '🇧🇻',
    },
    {
      id: 27,
      name: 'Belarus',
      continent: 'EU',
      prefixRegex: /^E[U-W][A-Z0-9/]*$/,
      flag: '🇧🇾',
    },
    {
      id: 29,
      name: 'Canary Islands',
      continent: 'AF',
      prefixRegex: /^E[A-H]8[A-Z0-9/]*$/,
      flag: '🇪🇸',
    },
    {
      id: 31,
      name: 'Phoenix Islands',
      continent: 'OC',
      prefixRegex: /^T31[A-Z0-9/]*$/,
      flag: '🇰🇮',
    },
    {
      id: 32,
      name: 'Ceuta and Melilla',
      continent: 'AF',
      prefixRegex: /^E[A-H]9[A-Z0-9/]*$/,
      flag: '🇪🇸',
    },
    {
      id: 33,
      name: 'Chagos Islands',
      continent: 'AF',
      prefixRegex: /^VQ9[A-Z0-9/]*$/,
      flag: '🇮🇴',
    },
    {
      id: 34,
      name: 'Chatham Islands',
      continent: 'OC',
      prefixRegex: /^ZL7[A-Z0-9/]*$/,
      flag: '🇳🇿',
    },
    {
      id: 35,
      name: 'Christmas Island',
      continent: 'OC',
      prefixRegex: /^VK9X[A-Z0-9/]*$/,
      flag: '🇨🇽',
    },
    {
      id: 36,
      name: 'Clipperton Island',
      continent: 'NA',
      prefixRegex: /^(FO|TX)[A-Z0-9/]*$/,
      flag: '🇵🇫',
    },
    {
      id: 37,
      name: 'Cocos Island',
      continent: 'NA',
      prefixRegex: /^TI9[A-Z0-9/]*$/,
      flag: '🇨🇷',
    },
    {
      id: 38,
      name: 'Cocos (Keeling) Islands',
      continent: 'OC',
      prefixRegex: /^VK9C[A-Z0-9/]*$/,
      flag: '🇨🇨',
    },
    {
      id: 40,
      name: 'Crete',
      continent: 'EU',
      prefixRegex: /^(SV|J4)9[A-Z0-9/]*$/,
      flag: '🇬🇷',
    },
    {
      id: 41,
      name: 'Crozet Islands',
      continent: 'AF',
      prefixRegex: /^FT\/W[A-Z0-9/]*$/,
      flag: '🇹🇫',
    },
    {
      id: 43,
      name: 'Desecheo Island',
      continent: 'NA',
      prefixRegex: /^KP5[A-Z0-9/]*$/,
      flag: '🇵🇷',
    },
    {
      id: 45,
      name: 'Dodecanese',
      continent: 'EU',
      prefixRegex: /^(SV|J4)5[A-Z0-9/]*$/,
      flag: '🇬🇷',
    },
    {
      id: 46,
      name: 'East Malaysia',
      continent: 'OC',
      prefixRegex: /^9M[68][A-Z0-9/]*$/,
      flag: '🇲🇾',
    },
    {
      id: 47,
      name: 'Easter Island',
      continent: 'SA',
      prefixRegex: /^CE0[A-Z0-9/]*$/,
      flag: '🇨🇱',
    },
    {
      id: 48,
      name: 'Line Islands',
      continent: 'OC',
      prefixRegex: /^T32[A-Z0-9/]*$/,
      flag: '🇰🇮',
    },
    {
      id: 49,
      name: 'Equatorial Guinea',
      continent: 'AF',
      prefixRegex: /^3C[A-Z0-9/]*$/,
      flag: '🇬🇶',
    },
    {
      id: 50,
      name: 'Mexico',
      continent: 'NA',
      prefixRegex: /^X[A-I][A-Z0-9/]*$/,
      flag: '🇲🇽',
    },
    {
      id: 51,
      name: 'Eritrea',
      continent: 'AF',
      prefixRegex: /^E3[A-Z0-9/]*$/,
      flag: '🇪🇷',
    },
    {
      id: 52,
      name: 'Estonia',
      continent: 'EU',
      prefixRegex: /^ES[A-Z0-9/]*$/,
      flag: '🇪🇪',
    },
    {
      id: 53,
      name: 'Ethiopia',
      continent: 'AF',
      prefixRegex: /^ET[A-Z0-9/]*$/,
      flag: '🇪🇹',
    },
    {
      id: 54,
      name: 'European Russia',
      continent: 'EU',
      prefixRegex: /^(U[A-I][1-7]|R[A-Z])[A-Z0-9/]*$/,
      flag: '🇷🇺',
    },
    {
      id: 56,
      name: 'Fernando de Noronha',
      continent: 'SA',
      prefixRegex: /^P[P-Y]0F[A-Z0-9/]*$/,
      flag: '🇧🇷',
    },
    {
      id: 60,
      name: 'Bahamas',
      continent: 'NA',
      prefixRegex: /^C6[A-Z0-9/]*$/,
      flag: '🇧🇸',
    },
    {
      id: 61,
      name: 'Franz Josef Land',
      continent: 'EU',
      prefixRegex: /^R1\/F[A-Z0-9/]*$/,
      flag: '🇷🇺',
    },
    {
      id: 62,
      name: 'Barbados',
      continent: 'NA',
      prefixRegex: /^8P[A-Z0-9/]*$/,
      flag: '🇧🇧',
    },
    {
      id: 63,
      name: 'French Guiana',
      continent: 'SA',
      prefixRegex: /^FY[A-Z0-9/]*$/,
      flag: '🇬🇫',
    },
    {
      id: 64,
      name: 'Bermuda',
      continent: 'NA',
      prefixRegex: /^VP9[A-Z0-9/]*$/,
      flag: '🇧🇲',
    },
    {
      id: 65,
      name: 'British Virgin Is.',
      continent: 'NA',
      prefixRegex: /^VP2V[A-Z0-9/]*$/,
      flag: '🇻🇬',
    },
    {
      id: 66,
      name: 'Belize',
      continent: 'NA',
      prefixRegex: /^V3[A-Z0-9/]*$/,
      flag: '🇧🇿',
    },
    {
      id: 69,
      name: 'Cayman Islands',
      continent: 'NA',
      prefixRegex: /^ZF[A-Z0-9/]*$/,
      flag: '🇰🇾',
    },
    {
      id: 70,
      name: 'Cuba',
      continent: 'NA',
      prefixRegex: /^C[MO][A-Z0-9/]*$/,
      flag: '🇨🇺',
    },
    {
      id: 71,
      name: 'Galápagos Islands',
      continent: 'SA',
      prefixRegex: /^H[CD]8[A-Z0-9/]*$/,
      flag: '🇪🇨',
    },
    {
      id: 72,
      name: 'Dominican Republic',
      continent: 'NA',
      prefixRegex: /^HI[A-Z0-9/]*$/,
      flag: '🇩🇴',
    },
    {
      id: 74,
      name: 'El Salvador',
      continent: 'NA',
      prefixRegex: /^(YS|HU)[A-Z0-9/]*$/,
      flag: '🇸🇻',
    },
    {
      id: 75,
      name: 'Georgia',
      continent: 'AS',
      prefixRegex: /^4L[A-Z0-9/]*$/,
      flag: '🇬🇪',
    },
    {
      id: 76,
      name: 'Guatemala',
      continent: 'NA',
      prefixRegex: /^T[GD][A-Z0-9/]*$/,
      flag: '🇬🇹',
    },
    {
      id: 77,
      name: 'Grenada',
      continent: 'NA',
      prefixRegex: /^J3[A-Z0-9/]*$/,
      flag: '🇬🇩',
    },
    {
      id: 78,
      name: 'Haiti',
      continent: 'NA',
      prefixRegex: /^HH[A-Z0-9/]*$/,
      flag: '🇭🇹',
    },
    {
      id: 79,
      name: 'Guadeloupe',
      continent: 'NA',
      prefixRegex: /^(FG|TO)[A-Z0-9/]*$/,
      flag: '🇬🇵',
    },
    {
      id: 80,
      name: 'Honduras',
      continent: 'NA',
      prefixRegex: /^H[QR][A-Z0-9/]*$/,
      flag: '🇭🇳',
    },
    {
      id: 82,
      name: 'Jamaica',
      continent: 'NA',
      prefixRegex: /^6Y[A-Z0-9/]*$/,
      flag: '🇯🇲',
    },
    {
      id: 84,
      name: 'Martinique',
      continent: 'NA',
      prefixRegex: /^(FM|TO)[A-Z0-9/]*$/,
      flag: '🇲🇶',
    },
    {
      id: 86,
      name: 'Nicaragua',
      continent: 'NA',
      prefixRegex: /^(YN|H[67T])[A-Z0-9/]*$/,
      flag: '🇳🇮',
    },
    {
      id: 88,
      name: 'Panama',
      continent: 'NA',
      prefixRegex: /^H[OP][A-Z0-9/]*$/,
      flag: '🇵🇦',
    },
    {
      id: 89,
      name: 'Turks and Caicos Islands',
      continent: 'NA',
      prefixRegex: /^VP5[A-Z0-9/]*$/,
      flag: '🇹🇨',
    },
    {
      id: 90,
      name: 'Trinidad and Tobago',
      continent: 'SA',
      prefixRegex: /^9[YZ][A-Z0-9/]*$/,
      flag: '🇹🇹',
    },
    {
      id: 91,
      name: 'Aruba',
      continent: 'SA',
      prefixRegex: /^P4[A-Z0-9/]*$/,
      flag: '🇦🇼',
    },
    {
      id: 94,
      name: 'Antigua and Barbuda',
      continent: 'NA',
      prefixRegex: /^V2[A-Z0-9/]*$/,
      flag: '🇦🇬',
    },
    {
      id: 95,
      name: 'Dominica',
      continent: 'NA',
      prefixRegex: /^J7[A-Z0-9/]*$/,
      flag: '🇩🇲',
    },
    {
      id: 96,
      name: 'Montserrat',
      continent: 'NA',
      prefixRegex: /^VP2M[A-Z0-9/]*$/,
      flag: '🇲🇸',
    },
    {
      id: 97,
      name: 'Saint Lucia',
      continent: 'NA',
      prefixRegex: /^J6[A-Z0-9/]*$/,
      flag: '🇱🇨',
    },
    {
      id: 98,
      name: 'Saint Vincent and the Grenadines',
      continent: 'NA',
      prefixRegex: /^J8[A-Z0-9/]*$/,
      flag: '🇻🇨',
    },
    {
      id: 99,
      name: 'Glorioso Islands',
      continent: 'AF',
      prefixRegex: /^(FT\/G|TO)[A-Z0-9/]*$/,
      flag: '🇹🇫',
    },
    {
      id: 100,
      name: 'Argentina',
      continent: 'SA',
      prefixRegex: /^L[O-W][A-Z0-9/]*$/,
      flag: '🇦🇷',
    },
    {
      id: 103,
      name: 'Guam',
      continent: 'OC',
      prefixRegex: /^KH2[A-Z0-9/]*$/,
      flag: '🇬🇺',
    },
    {
      id: 104,
      name: 'Bolivia',
      continent: 'SA',
      prefixRegex: /^CP[A-Z0-9/]*$/,
      flag: '🇧🇴',
    },
    {
      id: 105,
      name: 'Guantanamo Bay',
      continent: 'NA',
      prefixRegex: /^KG4[A-Z0-9/]*$/,
      flag: '🇺🇸',
    },
    {
      id: 106,
      name: 'Guernsey',
      continent: 'EU',
      prefixRegex: /^G[UP][A-Z0-9/]*$/,
      flag: '🇬🇬',
    },
    {
      id: 107,
      name: 'Guinea',
      continent: 'AF',
      prefixRegex: /^3X[A-Z0-9/]*$/,
      flag: '🇬🇳',
    },
    {
      id: 108,
      name: 'Brazil',
      continent: 'SA',
      prefixRegex: /^(P[P-Y]|Z[V-Z])[A-Z0-9/]*$/,
      flag: '🇧🇷',
    },
    {
      id: 109,
      name: 'Guinea-Bissau',
      continent: 'AF',
      prefixRegex: /^J5[A-Z0-9/]*$/,
      flag: '🇬🇼',
    },
    {
      id: 110,
      name: 'Hawaii',
      continent: 'OC',
      prefixRegex: /^KH[67][A-Z0-9/]*$/,
      flag: '🇺🇸',
    },
    {
      id: 111,
      name: 'Heard Island and McDonald Islands',
      continent: 'AF',
      prefixRegex: /^VK0[A-Z0-9/]*$/,
      flag: '🇭🇲',
    },
    {
      id: 112,
      name: 'Chile',
      continent: 'SA',
      prefixRegex: /^C[A-E][A-Z0-9/]*$/,
      flag: '🇨🇱',
    },
    {
      id: 114,
      name: 'Isle of Man',
      continent: 'EU',
      prefixRegex: /^G[DT][A-Z0-9/]*$/,
      flag: '🇮🇲',
    },
    {
      id: 116,
      name: 'Colombia',
      continent: 'SA',
      prefixRegex: /^(H[JK]|5[JK])[A-Z0-9/]*$/,
      flag: '🇨🇴',
    },
    {
      id: 117,
      name: 'International Telecommunication Union Headquarters',
      continent: 'EU',
      prefixRegex: /^4U[A-Z0-9/]*$/,
      flag: '🇺🇳',
    },
    {
      id: 118,
      name: 'Jan Mayen',
      continent: 'EU',
      prefixRegex: /^JX[A-Z0-9/]*$/,
      flag: '🇸🇯',
    },
    {
      id: 120,
      name: 'Ecuador',
      continent: 'SA',
      prefixRegex: /^H[CD][A-Z0-9/]*$/,
      flag: '🇪🇨',
    },
    {
      id: 122,
      name: 'Jersey',
      continent: 'EU',
      prefixRegex: /^G[JH][A-Z0-9/]*$/,
      flag: '🇯🇪',
    },
    {
      id: 123,
      name: 'Johnston Atoll',
      continent: 'OC',
      prefixRegex: /^KH3[A-Z0-9/]*$/,
      flag: '🇺🇸',
    },
    {
      id: 124,
      name: 'Juan de Nova and Europa Islands',
      continent: 'AF',
      prefixRegex: /^(FT\/J|E|TO)[A-Z0-9/]*$/,
      flag: '🇹🇫',
    },
    {
      id: 125,
      name: 'Juan Fernández Islands',
      continent: 'SA',
      prefixRegex: /^CE0[A-Z0-9/]*$/,
      flag: '🇨🇱',
    },
    {
      id: 126,
      name: 'Kaliningrad',
      continent: 'EU',
      prefixRegex: /^[UR]A2[A-Z0-9/]*$/,
      flag: '🇷🇺',
    },
    {
      id: 129,
      name: 'Guyana',
      continent: 'SA',
      prefixRegex: /^8R[A-Z0-9/]*$/,
      flag: '🇬🇾',
    },
    {
      id: 130,
      name: 'Kazakhstan',
      continent: 'AS',
      prefixRegex: /^U[N-Q][A-Z0-9/]*$/,
      flag: '🇰🇿',
    },
    {
      id: 131,
      name: 'Kerguelen Islands',
      continent: 'AF',
      prefixRegex: /^FT\/X[A-Z0-9/]*$/,
      flag: '🇹🇫',
    },
    {
      id: 132,
      name: 'Paraguay',
      continent: 'SA',
      prefixRegex: /^ZP[A-Z0-9/]*$/,
      flag: '🇵🇾',
    },
    {
      id: 133,
      name: 'Kermadec Islands',
      continent: 'OC',
      prefixRegex: /^ZL8[A-Z0-9/]*$/,
      flag: '🇳🇿',
    },
    {
      id: 135,
      name: 'Kyrgyzstan',
      continent: 'AS',
      prefixRegex: /^EX[A-Z0-9/]*$/,
      flag: '🇰🇬',
    },
    {
      id: 136,
      name: 'Peru',
      continent: 'SA',
      prefixRegex: /^O[A-C][A-Z0-9/]*$/,
      flag: '🇵🇪',
    },
    {
      id: 137,
      name: 'South Korea',
      continent: 'AS',
      prefixRegex: /^(HL|6[K-N])[A-Z0-9/]*$/,
      flag: '🇰🇷',
    },
    {
      id: 138,
      name: 'Kure Atoll',
      continent: 'OC',
      prefixRegex: /^KH7K[A-Z0-9/]*$/,
      flag: '🇺🇸',
    },
    {
      id: 140,
      name: 'Suriname',
      continent: 'SA',
      prefixRegex: /^PZ[A-Z0-9/]*$/,
      flag: '🇸🇷',
    },
    {
      id: 141,
      name: 'Falkland Islands',
      continent: 'SA',
      prefixRegex: /^VP8[A-Z0-9/]*$/,
      flag: '🇫🇰',
    },
    {
      id: 142,
      name: 'Lakshadweep',
      continent: 'AS',
      prefixRegex: /^VU7[A-Z0-9/]*$/,
      flag: '🇮🇳',
    },
    {
      id: 143,
      name: 'Laos',
      continent: 'AS',
      prefixRegex: /^XW[A-Z0-9/]*$/,
      flag: '🇱🇦',
    },
    {
      id: 144,
      name: 'Uruguay',
      continent: 'SA',
      prefixRegex: /^C[V-X][A-Z0-9/]*$/,
      flag: '🇺🇾',
    },
    {
      id: 145,
      name: 'Latvia',
      continent: 'EU',
      prefixRegex: /^YL[A-Z0-9/]*$/,
      flag: '🇱🇻',
    },
    {
      id: 146,
      name: 'Lithuania',
      continent: 'EU',
      prefixRegex: /^LY[A-Z0-9/]*$/,
      flag: '🇱🇹',
    },
    {
      id: 147,
      name: 'Lord Howe Island',
      continent: 'OC',
      prefixRegex: /^VK9L[A-Z0-9/]*$/,
      flag: '🇦🇺',
    },
    {
      id: 148,
      name: 'Venezuela',
      continent: 'SA',
      prefixRegex: /^(Y[V-Y]|4M)[A-Z0-9/]*$/,
      flag: '🇻🇪',
    },
    {
      id: 149,
      name: 'Azores',
      continent: 'EU',
      prefixRegex: /^CU[A-Z0-9/]*$/,
      flag: '🇵🇹',
    },
    {
      id: 150,
      name: 'Australia',
      continent: 'OC',
      prefixRegex: /^(VK|AX)[A-Z0-9/]*$/,
      flag: '🇦🇺',
    },
    {
      id: 152,
      name: 'Macao',
      continent: 'AS',
      prefixRegex: /^XX9[A-Z0-9/]*$/,
      flag: '🇲🇴',
    },
    {
      id: 153,
      name: 'Macquarie Island',
      continent: 'OC',
      prefixRegex: /^VK0[A-Z0-9/]*$/,
      flag: '🇦🇺',
    },
    {
      id: 157,
      name: 'Nauru',
      continent: 'OC',
      prefixRegex: /^C2[A-Z0-9/]*$/,
      flag: '🇳🇷',
    },
    {
      id: 158,
      name: 'Vanuatu',
      continent: 'OC',
      prefixRegex: /^YJ[A-Z0-9/]*$/,
      flag: '🇻🇺',
    },
    {
      id: 159,
      name: 'Maldives',
      continent: 'AS',
      prefixRegex: /^8Q[A-Z0-9/]*$/,
      flag: '🇲🇻',
    },
    {
      id: 160,
      name: 'Tonga',
      continent: 'OC',
      prefixRegex: /^A3[A-Z0-9/]*$/,
      flag: '🇹🇴',
    },
    {
      id: 161,
      name: 'Malpelo Island',
      continent: 'SA',
      prefixRegex: /^HK0[A-Z0-9/]*$/,
      flag: '🇨🇴',
    },
    {
      id: 162,
      name: 'New Caledonia',
      continent: 'OC',
      prefixRegex: /^(FK|TX)[A-Z0-9/]*$/,
      flag: '🇳🇨',
    },
    {
      id: 163,
      name: 'Papua New Guinea',
      continent: 'OC',
      prefixRegex: /^P2[A-Z0-9/]*$/,
      flag: '🇵🇬',
    },
    {
      id: 165,
      name: 'Mauritius',
      continent: 'AF',
      prefixRegex: /^3B8[A-Z0-9/]*$/,
      flag: '🇲🇺',
    },
    {
      id: 166,
      name: 'Mariana Islands',
      continent: 'OC',
      prefixRegex: /^KH0[A-Z0-9/]*$/,
      flag: '🇲🇵',
    },
    {
      id: 167,
      name: 'Märket Island',
      continent: 'EU',
      prefixRegex: /^OJ0[A-Z0-9/]*$/,
      flag: '',
    },
    {
      id: 168,
      name: 'Marshall Islands',
      continent: 'OC',
      prefixRegex: /^V7[A-Z0-9/]*$/,
      flag: '🇲🇭',
    },
    {
      id: 169,
      name: 'Mayotte',
      continent: 'AF',
      prefixRegex: /^(FH|TO)[A-Z0-9/]*$/,
      flag: '🇾🇹',
    },
    {
      id: 170,
      name: 'New Zealand',
      continent: 'OC',
      prefixRegex: /^Z[L-M][A-Z0-9/]*$/,
      flag: '🇳🇿',
    },
    {
      id: 171,
      name: 'Mellish Reef',
      continent: 'OC',
      prefixRegex: /^VK9M[A-Z0-9/]*$/,
      flag: '🇦🇺',
    },
    {
      id: 172,
      name: 'Pitcairn Islands',
      continent: 'OC',
      prefixRegex: /^VP6[A-Z0-9/]*$/,
      flag: '🇵🇳',
    },
    {
      id: 173,
      name: 'Micronesia',
      continent: 'OC',
      prefixRegex: /^V6[A-Z0-9/]*$/,
      flag: '🇫🇲',
    },
    {
      id: 174,
      name: 'Midway Atoll',
      continent: 'OC',
      prefixRegex: /^KH4[A-Z0-9/]*$/,
      flag: '🇺🇸',
    },
    {
      id: 175,
      name: 'French Polynesia',
      continent: 'OC',
      prefixRegex: /^(FO|TX)[A-Z0-9/]*$/,
      flag: '🇵🇫',
    },
    {
      id: 176,
      name: 'Fiji',
      continent: 'OC',
      prefixRegex: /^3D2[A-Z0-9/]*$/,
      flag: '🇫🇯',
    },
    {
      id: 177,
      name: 'Minami-Tori-shima',
      continent: 'OC',
      prefixRegex: /^JD1[A-Z0-9/]*$/,
      flag: '🇯🇵',
    },
    {
      id: 179,
      name: 'Moldova',
      continent: 'EU',
      prefixRegex: /^ER[A-Z0-9/]*$/,
      flag: '🇲🇩',
    },
    {
      id: 180,
      name: 'Mount Athos',
      continent: 'EU',
      prefixRegex: /^SV\/A[A-Z0-9/]*$/,
      flag: '🇬🇷',
    },
    {
      id: 181,
      name: 'Mozambique',
      continent: 'AF',
      prefixRegex: /^C[89][A-Z0-9/]*$/,
      flag: '🇲🇿',
    },
    {
      id: 182,
      name: 'Navassa Island',
      continent: 'NA',
      prefixRegex: /^KP1[A-Z0-9/]*$/,
      flag: '🇺🇸',
    },
    {
      id: 185,
      name: 'Solomon Islands',
      continent: 'OC',
      prefixRegex: /^H4[A-Z0-9/]*$/,
      flag: '🇸🇧',
    },
    {
      id: 187,
      name: 'Niger',
      continent: 'AF',
      prefixRegex: /^5U[A-Z0-9/]*$/,
      flag: '🇳🇪',
    },
    {
      id: 188,
      name: 'Niue',
      continent: 'OC',
      prefixRegex: /^E6[A-Z0-9/]*$/,
      flag: '🇳🇺',
    },
    {
      id: 189,
      name: 'Norfolk Island',
      continent: 'OC',
      prefixRegex: /^VK9N[A-Z0-9/]*$/,
      flag: '🇦🇺',
    },
    {
      id: 190,
      name: 'Samoa',
      continent: 'OC',
      prefixRegex: /^5W[A-Z0-9/]*$/,
      flag: '🇼🇸',
    },
    {
      id: 191,
      name: 'North Cook Islands',
      continent: 'OC',
      prefixRegex: /^E5[A-Z0-9/]*$/,
      flag: '🇨🇰',
    },
    {
      id: 192,
      name: 'Ogasawara Islands',
      continent: 'AS',
      prefixRegex: /^JD1[A-Z0-9/]*$/,
      flag: '🇯🇵',
    },
    {
      id: 195,
      name: 'Annobón',
      continent: 'AF',
      prefixRegex: /^3C0[A-Z0-9/]*$/,
      flag: '🇬🇶',
    },
    {
      id: 197,
      name: 'Palmyra and Jarvis Islands',
      continent: 'OC',
      prefixRegex: /^KH5[A-Z0-9/]*$/,
      flag: '🇺🇸',
    },
    {
      id: 199,
      name: 'Peter I Island',
      continent: 'AN',
      prefixRegex: /^3Y[A-Z0-9/]*$/,
      flag: '🇧🇻',
    },
    {
      id: 201,
      name: 'Prince Edward and Marion Islands',
      continent: 'AF',
      prefixRegex: /^ZS8[A-Z0-9/]*$/,
      flag: '🇿🇦',
    },
    {
      id: 202,
      name: 'Puerto Rico',
      continent: 'NA',
      prefixRegex: /^KP[34][A-Z0-9/]*$/,
      flag: '🇵🇷',
    },
    {
      id: 203,
      name: 'Andorra',
      continent: 'EU',
      prefixRegex: /^C3[A-Z0-9/]*$/,
      flag: '🇦🇩',
    },
    {
      id: 204,
      name: 'Revillagigedo Islands',
      continent: 'NA',
      prefixRegex: /^X[A-I]4[A-Z0-9/]*$/,
      flag: '🇲🇽',
    },
    {
      id: 205,
      name: 'Ascension Island',
      continent: 'AF',
      prefixRegex: /^ZD8[A-Z0-9/]*$/,
      flag: '🇸🇭',
    },
    {
      id: 206,
      name: 'Austria',
      continent: 'EU',
      prefixRegex: /^OE[A-Z0-9/]*$/,
      flag: '🇦🇹',
    },
    {
      id: 207,
      name: 'Rodrigues Island',
      continent: 'AF',
      prefixRegex: /^3B9[A-Z0-9/]*$/,
      flag: '🇲🇺',
    },
    {
      id: 209,
      name: 'Belgium',
      continent: 'EU',
      prefixRegex: /^O[N-T][A-Z0-9/]*$/,
      flag: '🇧🇪',
    },
    {
      id: 211,
      name: 'Sable Island',
      continent: 'NA',
      prefixRegex: /^CY0[A-Z0-9/]*$/,
      flag: '🇨🇦',
    },
    {
      id: 212,
      name: 'Bulgaria',
      continent: 'EU',
      prefixRegex: /^LZ[A-Z0-9/]*$/,
      flag: '🇧🇬',
    },
    {
      id: 213,
      name: 'Saint Martin',
      continent: 'NA',
      prefixRegex: /^(FS|TO)[A-Z0-9/]*$/,
      flag: '🇫🇷',
    },
    {
      id: 214,
      name: 'Corsica',
      continent: 'EU',
      prefixRegex: /^TK[A-Z0-9/]*$/,
      flag: '🇫🇷',
    },
    {
      id: 215,
      name: 'Cyprus',
      continent: 'AS',
      prefixRegex: /^(5B|C4|P3)[A-Z0-9/]*$/,
      flag: '🇨🇾',
    },
    {
      id: 216,
      name: 'San Andrés and Providencia',
      continent: 'NA',
      prefixRegex: /^HK0[A-Z0-9/]*$/,
      flag: '🇨🇴',
    },
    {
      id: 217,
      name: 'Desventuradas Islands',
      continent: 'SA',
      prefixRegex: /^CE0[A-Z0-9/]*$/,
      flag: '🇨🇱',
    },
    {
      id: 219,
      name: 'Sao Tome and Principe',
      continent: 'AF',
      prefixRegex: /^S9[A-Z0-9/]*$/,
      flag: '🇸🇹',
    },
    {
      id: 221,
      name: 'Denmark',
      continent: 'EU',
      prefixRegex: /^O[U-WZ][A-Z0-9/]*$/,
      flag: '🇩🇰',
    },
    {
      id: 222,
      name: 'Faroe Islands',
      continent: 'EU',
      prefixRegex: /^OY[A-Z0-9/]*$/,
      flag: '🇫🇴',
    },
    {
      id: 223,
      name: 'England',
      continent: 'EU',
      prefixRegex: /^(G|GX|M)[A-Z0-9/]*$/,
      flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    },
    {
      id: 224,
      name: 'Finland',
      continent: 'EU',
      prefixRegex: /^O[F-I][A-Z0-9/]*$/,
      flag: '🇫🇮',
    },
    {
      id: 225,
      name: 'Sardinia',
      continent: 'EU',
      prefixRegex: /^I[SM]0[A-Z0-9/]*$/,
      flag: '🇮🇹',
    },
    {
      id: 227,
      name: 'France',
      continent: 'EU',
      prefixRegex: /^F[A-Z0-9/]*$/,
      flag: '🇫🇷',
    },
    {
      id: 230,
      name: 'Germany',
      continent: 'EU',
      prefixRegex: /^D[A-R][A-Z0-9/]*$/,
      flag: '🇩🇪',
    },
    {
      id: 232,
      name: 'Somalia',
      continent: 'AF',
      prefixRegex: /^(T5|6O)[A-Z0-9/]*$/,
      flag: '🇸🇴',
    },
    {
      id: 233,
      name: 'Gibraltar',
      continent: 'EU',
      prefixRegex: /^ZB2[A-Z0-9/]*$/,
      flag: '🇬🇮',
    },
    {
      id: 234,
      name: 'South Cook Islands',
      continent: 'OC',
      prefixRegex: /^E5[A-Z0-9/]*$/,
      flag: '🇨🇰',
    },
    {
      id: 235,
      name: 'South Georgia Island',
      continent: 'SA',
      prefixRegex: /^(VP8|LU)[A-Z0-9/]*$/,
      flag: '🇬🇧',
    },
    {
      id: 236,
      name: 'Greece',
      continent: 'EU',
      prefixRegex: /^(S[V-Z]|J4)[A-Z0-9/]*$/,
      flag: '🇬🇷',
    },
    {
      id: 237,
      name: 'Greenland',
      continent: 'NA',
      prefixRegex: /^OX[A-Z0-9/]*$/,
      flag: '🇬🇱',
    },
    {
      id: 238,
      name: 'South Orkney Islands',
      continent: 'SA',
      prefixRegex: /^(VP8|LU)[A-Z0-9/]*$/,
      flag: '🇦🇶',
    },
    {
      id: 239,
      name: 'Hungary',
      continent: 'EU',
      prefixRegex: /^H[AG][A-Z0-9/]*$/,
      flag: '🇭🇺',
    },
    {
      id: 240,
      name: 'South Sandwich Islands',
      continent: 'SA',
      prefixRegex: /^(VP8|LU)[A-Z0-9/]*$/,
      flag: '🇬🇧',
    },
    {
      id: 241,
      name: 'South Shetland Islands',
      continent: 'SA',
      prefixRegex: /^(VP8|LU|CE9|HF0|4K1)[A-Z0-9/]*$/,
      flag: '🇦🇶',
    },
    {
      id: 242,
      name: 'Iceland',
      continent: 'EU',
      prefixRegex: /^TF[A-Z0-9/]*$/,
      flag: '🇮🇸',
    },
    {
      id: 245,
      name: 'Ireland',
      continent: 'EU',
      prefixRegex: /^E[IJ][A-Z0-9/]*$/,
      flag: '🇮🇪',
    },
    {
      id: 246,
      name: 'Sovereign Military Order of Malta',
      continent: 'EU',
      prefixRegex: /^1A[A-Z0-9/]*$/,
      flag: '',
    },
    {
      id: 247,
      name: 'Spratly Islands',
      continent: 'AS',
      prefixRegex: null,
      flag: '',
    },
    {
      id: 248,
      name: 'Italy',
      continent: 'EU',
      prefixRegex: /^I[A-Z0-9/]*$/,
      flag: '🇮🇹',
    },
    {
      id: 249,
      name: 'Saint Kitts and Nevis',
      continent: 'NA',
      prefixRegex: /^V4[A-Z0-9/]*$/,
      flag: '🇰🇳',
    },
    {
      id: 250,
      name: 'St. Helena',
      continent: 'AF',
      prefixRegex: /^ZD7[A-Z0-9/]*$/,
      flag: '🇸🇭',
    },
    {
      id: 251,
      name: 'Liechtenstein',
      continent: 'EU',
      prefixRegex: /^HB0[A-Z0-9/]*$/,
      flag: '🇱🇮',
    },
    {
      id: 252,
      name: 'St. Paul Island',
      continent: 'NA',
      prefixRegex: /^CY9[A-Z0-9/]*$/,
      flag: '🇨🇦',
    },
    {
      id: 253,
      name: 'Saint Peter and Saint Paul Archipelago',
      continent: 'SA',
      prefixRegex: /^P[P-Y]0S[A-Z0-9/]*$/,
      flag: '🇧🇷',
    },
    {
      id: 254,
      name: 'Luxembourg',
      continent: 'EU',
      prefixRegex: /^LX[A-Z0-9/]*$/,
      flag: '🇱🇺',
    },
    {
      id: 256,
      name: 'Madeira',
      continent: 'AF',
      prefixRegex: /^CT3[A-Z0-9/]*$/,
      flag: '🇵🇹',
    },
    {
      id: 257,
      name: 'Malta',
      continent: 'EU',
      prefixRegex: /^9H[A-Z0-9/]*$/,
      flag: '🇲🇹',
    },
    {
      id: 259,
      name: 'Svalbard',
      continent: 'EU',
      prefixRegex: /^JW[A-Z0-9/]*$/,
      flag: '🇸🇯',
    },
    {
      id: 260,
      name: 'Monaco',
      continent: 'EU',
      prefixRegex: /^3A[A-Z0-9/]*$/,
      flag: '🇲🇨',
    },
    {
      id: 262,
      name: 'Tajikistan',
      continent: 'AS',
      prefixRegex: /^EY[A-Z0-9/]*$/,
      flag: '🇹🇯',
    },
    {
      id: 263,
      name: 'Netherlands',
      continent: 'EU',
      prefixRegex: /^P[A-I][A-Z0-9/]*$/,
      flag: '🇳🇱',
    },
    {
      id: 265,
      name: 'Northern Ireland',
      continent: 'EU',
      prefixRegex: /^G[IN][A-Z0-9/]*$/,
      flag: '🏴󠁧󠁢󠁮󠁩󠁲󠁿',
    },
    {
      id: 266,
      name: 'Norway',
      continent: 'EU',
      prefixRegex: /^L[A-N][A-Z0-9/]*$/,
      flag: '🇳🇴',
    },
    {
      id: 269,
      name: 'Poland',
      continent: 'EU',
      prefixRegex: /^S[N-R][A-Z0-9/]*$/,
      flag: '🇵🇱',
    },
    {
      id: 270,
      name: 'Tokelau',
      continent: 'OC',
      prefixRegex: /^ZK3[A-Z0-9/]*$/,
      flag: '🇹🇰',
    },
    {
      id: 272,
      name: 'Portugal',
      continent: 'EU',
      prefixRegex: /^CT[A-Z0-9/]*$/,
      flag: '🇵🇹',
    },
    {
      id: 273,
      name: 'Trindade and Martin Vaz',
      continent: 'SA',
      prefixRegex: /^P[P-Y]0T[A-Z0-9/]*$/,
      flag: '🇧🇷',
    },
    {
      id: 274,
      name: 'Tristan da Cunha and Gough Islands',
      continent: 'AF',
      prefixRegex: /^ZD9[A-Z0-9/]*$/,
      flag: '🇸🇭',
    },
    {
      id: 275,
      name: 'Romania',
      continent: 'EU',
      prefixRegex: /^Y[O-R][A-Z0-9/]*$/,
      flag: '🇷🇴',
    },
    {
      id: 276,
      name: 'Tromelin Island',
      continent: 'AF',
      prefixRegex: /^(FT\/T|TO)[A-Z0-9/]*$/,
      flag: '🇹🇫',
    },
    {
      id: 277,
      name: 'Saint Pierre and Miquelon',
      continent: 'NA',
      prefixRegex: /^FP[A-Z0-9/]*$/,
      flag: '🇵🇲',
    },
    {
      id: 278,
      name: 'San Marino',
      continent: 'EU',
      prefixRegex: /^T7[A-Z0-9/]*$/,
      flag: '🇸🇲',
    },
    {
      id: 279,
      name: 'Scotland',
      continent: 'EU',
      prefixRegex: /^G[MS][A-Z0-9/]*$/,
      flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    },
    {
      id: 280,
      name: 'Turkmenistan',
      continent: 'AS',
      prefixRegex: /^EZ[A-Z0-9/]*$/,
      flag: '🇹🇲',
    },
    {
      id: 281,
      name: 'Spain',
      continent: 'EU',
      prefixRegex: /^E[A-H][A-Z0-9/]*$/,
      flag: '🇪🇸',
    },
    {
      id: 282,
      name: 'Tuvalu',
      continent: 'OC',
      prefixRegex: /^T2[A-Z0-9/]*$/,
      flag: '🇹🇻',
    },
    {
      id: 283,
      name: 'Sovereign Base Areas of Akrotiri and Dhekelia',
      continent: 'AS',
      prefixRegex: /^ZC4[A-Z0-9/]*$/,
      flag: '🇬🇧',
    },
    {
      id: 284,
      name: 'Sweden',
      continent: 'EU',
      prefixRegex: /^(S[A-M]|[78]S)[A-Z0-9/]*$/,
      flag: '🇸🇪',
    },
    {
      id: 285,
      name: 'US Virgin Islands',
      continent: 'NA',
      prefixRegex: /^KP2[A-Z0-9/]*$/,
      flag: '🇻🇮',
    },
    {
      id: 286,
      name: 'Uganda',
      continent: 'AF',
      prefixRegex: /^5X[A-Z0-9/]*$/,
      flag: '🇺🇬',
    },
    {
      id: 287,
      name: 'Switzerland',
      continent: 'EU',
      prefixRegex: /^HB[A-Z0-9/]*$/,
      flag: '🇨🇭',
    },
    {
      id: 288,
      name: 'Ukraine',
      continent: 'EU',
      prefixRegex: /^(U[R-Z]|E[M-O])[A-Z0-9/]*$/,
      flag: '🇺🇦',
    },
    {
      id: 289,
      name: 'United Nations Headquarters',
      continent: 'NA',
      prefixRegex: /^4U[A-Z0-9/]*$/,
      flag: '🇺🇳',
    },
    {
      id: 291,
      name: 'United States',
      continent: 'NA',
      prefixRegex: /^(K|W|N|A[A-K])[A-Z0-9/]*$/,
      flag: '🇺🇸',
    },
    {
      id: 292,
      name: 'Uzbekistan',
      continent: 'AS',
      prefixRegex: /^U[J-M][A-Z0-9/]*$/,
      flag: '🇺🇿',
    },
    {
      id: 293,
      name: 'Viet Nam',
      continent: 'AS',
      prefixRegex: /^(3W|XV)[A-Z0-9/]*$/,
      flag: '🇻🇳',
    },
    {
      id: 294,
      name: 'Wales',
      continent: 'EU',
      prefixRegex: /^G[WC][A-Z0-9/]*$/,
      flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    },
    {
      id: 295,
      name: 'Vatican',
      continent: 'EU',
      prefixRegex: /^HV[A-Z0-9/]*$/,
      flag: '🇻🇦',
    },
    {
      id: 296,
      name: 'Serbia',
      continent: 'EU',
      prefixRegex: /^Y[TU][A-Z0-9/]*$/,
      flag: '🇷🇸',
    },
    {
      id: 297,
      name: 'Wake Island',
      continent: 'OC',
      prefixRegex: /^KH9[A-Z0-9/]*$/,
      flag: '🇺🇸',
    },
    {
      id: 298,
      name: 'Wallis and Futuna Islands',
      continent: 'OC',
      prefixRegex: /^FW[A-Z0-9/]*$/,
      flag: '🇼🇫',
    },
    {
      id: 299,
      name: 'West Malaysia',
      continent: 'AS',
      prefixRegex: /^9M[24][A-Z0-9/]*$/,
      flag: '🇲🇾',
    },
    {
      id: 301,
      name: 'Gilbert Islands',
      continent: 'OC',
      prefixRegex: /^T30[A-Z0-9/]*$/,
      flag: '🇰🇮',
    },
    {
      id: 302,
      name: 'Western Sahara',
      continent: 'AF',
      prefixRegex: /^S0[A-Z0-9/]*$/,
      flag: '🇪🇭',
    },
    {
      id: 303,
      name: 'Willis Island',
      continent: 'OC',
      prefixRegex: /^VK9W[A-Z0-9/]*$/,
      flag: '🇦🇺',
    },
    {
      id: 304,
      name: 'Bahrain',
      continent: 'AS',
      prefixRegex: /^A9[A-Z0-9/]*$/,
      flag: '🇧🇭',
    },
    {
      id: 305,
      name: 'Bangladesh',
      continent: 'AS',
      prefixRegex: /^S2[A-Z0-9/]*$/,
      flag: '🇧🇩',
    },
    {
      id: 306,
      name: 'Bhutan',
      continent: 'AS',
      prefixRegex: /^A5[A-Z0-9/]*$/,
      flag: '🇧🇹',
    },
    {
      id: 308,
      name: 'Costa Rica',
      continent: 'NA',
      prefixRegex: /^T[IE][A-Z0-9/]*$/,
      flag: '🇨🇷',
    },
    {
      id: 309,
      name: 'Myanmar',
      continent: 'AS',
      prefixRegex: /^X[YZ][A-Z0-9/]*$/,
      flag: '🇲🇲',
    },
    {
      id: 312,
      name: 'Cambodia',
      continent: 'AS',
      prefixRegex: /^XU[A-Z0-9/]*$/,
      flag: '🇰🇭',
    },
    {
      id: 315,
      name: 'Sri Lanka',
      continent: 'AS',
      prefixRegex: /^4S[A-Z0-9/]*$/,
      flag: '🇱🇰',
    },
    {
      id: 318,
      name: 'China',
      continent: 'AS',
      prefixRegex: /^B[A-Z0-9/]*$/,
      flag: '🇨🇳',
    },
    {
      id: 321,
      name: 'Hong Kong',
      continent: 'AS',
      prefixRegex: /^VR[A-Z0-9/]*$/,
      flag: '🇭🇰',
    },
    {
      id: 324,
      name: 'India',
      continent: 'AS',
      prefixRegex: /^VU[A-Z0-9/]*$/,
      flag: '🇮🇳',
    },
    {
      id: 327,
      name: 'Indonesia',
      continent: 'OC',
      prefixRegex: /^Y[B-H][A-Z0-9/]*$/,
      flag: '🇮🇩',
    },
    {
      id: 330,
      name: 'Iran',
      continent: 'AS',
      prefixRegex: /^E[PQ][A-Z0-9/]*$/,
      flag: '🇮🇷',
    },
    {
      id: 333,
      name: 'Iraq',
      continent: 'AS',
      prefixRegex: /^YI[A-Z0-9/]*$/,
      flag: '🇮🇶',
    },
    {
      id: 336,
      name: 'Israel',
      continent: 'AS',
      prefixRegex: /^4[XZ][A-Z0-9/]*$/,
      flag: '🇮🇱',
    },
    {
      id: 339,
      name: 'Japan',
      continent: 'AS',
      prefixRegex: /^(J[A-S]|7[J-N])[A-Z0-9/]*$/,
      flag: '🇯🇵',
    },
    {
      id: 342,
      name: 'Jordan',
      continent: 'AS',
      prefixRegex: /^JY[A-Z0-9/]*$/,
      flag: '🇯🇴',
    },
    {
      id: 344,
      name: "Democratic People's Republic of Korea",
      continent: 'AS',
      prefixRegex: /^P5[A-Z0-9/]*$/,
      flag: '🇰🇵',
    },
    {
      id: 345,
      name: 'Brunei Darussalam',
      continent: 'OC',
      prefixRegex: /^V8[A-Z0-9/]*$/,
      flag: '🇧🇳',
    },
    {
      id: 348,
      name: 'Kuwait',
      continent: 'AS',
      prefixRegex: /^9K[A-Z0-9/]*$/,
      flag: '🇰🇼',
    },
    {
      id: 354,
      name: 'Lebanon',
      continent: 'AS',
      prefixRegex: /^OD[A-Z0-9/]*$/,
      flag: '🇱🇧',
    },
    {
      id: 363,
      name: 'Mongolia',
      continent: 'AS',
      prefixRegex: /^J[T-V][A-Z0-9/]*$/,
      flag: '🇲🇳',
    },
    {
      id: 369,
      name: 'Nepal',
      continent: 'AS',
      prefixRegex: /^9N[A-Z0-9/]*$/,
      flag: '🇳🇵',
    },
    {
      id: 370,
      name: 'Oman',
      continent: 'AS',
      prefixRegex: /^A4[A-Z0-9/]*$/,
      flag: '🇴🇲',
    },
    {
      id: 372,
      name: 'Pakistan',
      continent: 'AS',
      prefixRegex: /^AP[A-Z0-9/]*$/,
      flag: '🇵🇰',
    },
    {
      id: 375,
      name: 'Philippines',
      continent: 'OC',
      prefixRegex: /^(D[U-Z]|4[D-I])[A-Z0-9/]*$/,
      flag: '🇵🇭',
    },
    {
      id: 376,
      name: 'Qatar',
      continent: 'AS',
      prefixRegex: /^A7[A-Z0-9/]*$/,
      flag: '🇶🇦',
    },
    {
      id: 378,
      name: 'Saudi Arabia',
      continent: 'AS',
      prefixRegex: /^HZ[A-Z0-9/]*$/,
      flag: '🇸🇦',
    },
    {
      id: 379,
      name: 'Seychelles',
      continent: 'AF',
      prefixRegex: /^S7[A-Z0-9/]*$/,
      flag: '🇸🇨',
    },
    {
      id: 381,
      name: 'Singapore',
      continent: 'AS',
      prefixRegex: /^9V[A-Z0-9/]*$/,
      flag: '🇸🇬',
    },
    {
      id: 382,
      name: 'Djibouti',
      continent: 'AF',
      prefixRegex: /^J2[A-Z0-9/]*$/,
      flag: '🇩🇯',
    },
    {
      id: 384,
      name: 'Syria',
      continent: 'AS',
      prefixRegex: /^YK[A-Z0-9/]*$/,
      flag: '🇸🇾',
    },
    {
      id: 386,
      name: 'Taiwan',
      continent: 'AS',
      prefixRegex: /^B[U-X][A-Z0-9/]*$/,
      flag: '🇹🇼',
    },
    {
      id: 387,
      name: 'Thailand',
      continent: 'AS',
      prefixRegex: /^(HS|E2)[A-Z0-9/]*$/,
      flag: '🇹🇭',
    },
    {
      id: 390,
      name: 'Turkey',
      continent: 'EU',
      prefixRegex: /^T[A-C][A-Z0-9/]*$/,
      flag: '🇹🇷',
    },
    {
      id: 391,
      name: 'United Arab Emirates',
      continent: 'AS',
      prefixRegex: /^A6[A-Z0-9/]*$/,
      flag: '🇦🇪',
    },
    {
      id: 400,
      name: 'Algeria',
      continent: 'AF',
      prefixRegex: /^7[T-Y][A-Z0-9/]*$/,
      flag: '🇩🇿',
    },
    {
      id: 401,
      name: 'Angola',
      continent: 'AF',
      prefixRegex: /^D[23][A-Z0-9/]*$/,
      flag: '🇦🇴',
    },
    {
      id: 402,
      name: 'Botswana',
      continent: 'AF',
      prefixRegex: /^A2[A-Z0-9/]*$/,
      flag: '🇧🇼',
    },
    {
      id: 404,
      name: 'Burundi',
      continent: 'AF',
      prefixRegex: /^9U[A-Z0-9/]*$/,
      flag: '🇧🇮',
    },
    {
      id: 406,
      name: 'Cameroon',
      continent: 'AF',
      prefixRegex: /^TJ[A-Z0-9/]*$/,
      flag: '🇨🇲',
    },
    {
      id: 408,
      name: 'Central African Republic',
      continent: 'AF',
      prefixRegex: /^TL[A-Z0-9/]*$/,
      flag: '🇨🇫',
    },
    {
      id: 409,
      name: 'Cape Verde',
      continent: 'AF',
      prefixRegex: /^D4[A-Z0-9/]*$/,
      flag: '🇨🇻',
    },
    {
      id: 410,
      name: 'Chad',
      continent: 'AF',
      prefixRegex: /^TT[A-Z0-9/]*$/,
      flag: '🇹🇩',
    },
    {
      id: 411,
      name: 'Comoros',
      continent: 'AF',
      prefixRegex: /^D6[A-Z0-9/]*$/,
      flag: '🇰🇲',
    },
    {
      id: 412,
      name: 'Republic of the Congo',
      continent: 'AF',
      prefixRegex: /^TN[A-Z0-9/]*$/,
      flag: '🇨🇬',
    },
    {
      id: 414,
      name: 'Democratic Republic of the Congo',
      continent: 'AF',
      prefixRegex: /^9[Q-T][A-Z0-9/]*$/,
      flag: '🇨🇩',
    },
    {
      id: 416,
      name: 'Benin',
      continent: 'AF',
      prefixRegex: /^TY[A-Z0-9/]*$/,
      flag: '🇧🇯',
    },
    {
      id: 420,
      name: 'Gabon',
      continent: 'AF',
      prefixRegex: /^TR[A-Z0-9/]*$/,
      flag: '🇬🇦',
    },
    {
      id: 422,
      name: 'The Gambia',
      continent: 'AF',
      prefixRegex: /^C5[A-Z0-9/]*$/,
      flag: '🇬🇲',
    },
    {
      id: 424,
      name: 'Ghana',
      continent: 'AF',
      prefixRegex: /^9G[A-Z0-9/]*$/,
      flag: '🇬🇭',
    },
    {
      id: 428,
      name: "Côte d'Ivoire",
      continent: 'AF',
      prefixRegex: /^TU[A-Z0-9/]*$/,
      flag: '🇨🇮',
    },
    {
      id: 430,
      name: 'Kenya',
      continent: 'AF',
      prefixRegex: /^5[YZ][A-Z0-9/]*$/,
      flag: '🇰🇪',
    },
    {
      id: 432,
      name: 'Lesotho',
      continent: 'AF',
      prefixRegex: /^7P[A-Z0-9/]*$/,
      flag: '🇱🇸',
    },
    {
      id: 434,
      name: 'Liberia',
      continent: 'AF',
      prefixRegex: /^EL[A-Z0-9/]*$/,
      flag: '🇱🇷',
    },
    {
      id: 436,
      name: 'Libya',
      continent: 'AF',
      prefixRegex: /^5A[A-Z0-9/]*$/,
      flag: '🇱🇾',
    },
    {
      id: 438,
      name: 'Madagascar',
      continent: 'AF',
      prefixRegex: /^5R[A-Z0-9/]*$/,
      flag: '🇲🇬',
    },
    {
      id: 440,
      name: 'Malawi',
      continent: 'AF',
      prefixRegex: /^7Q[A-Z0-9/]*$/,
      flag: '🇲🇼',
    },
    {
      id: 442,
      name: 'Mali',
      continent: 'AF',
      prefixRegex: /^TZ[A-Z0-9/]*$/,
      flag: '🇲🇱',
    },
    {
      id: 444,
      name: 'Mauritania',
      continent: 'AF',
      prefixRegex: /^5T[A-Z0-9/]*$/,
      flag: '🇲🇷',
    },
    {
      id: 446,
      name: 'Morocco',
      continent: 'AF',
      prefixRegex: /^CN[A-Z0-9/]*$/,
      flag: '🇲🇦',
    },
    {
      id: 450,
      name: 'Nigeria',
      continent: 'AF',
      prefixRegex: /^5N[A-Z0-9/]*$/,
      flag: '🇳🇬',
    },
    {
      id: 452,
      name: 'Zimbabwe',
      continent: 'AF',
      prefixRegex: /^Z2[A-Z0-9/]*$/,
      flag: '🇿🇼',
    },
    {
      id: 453,
      name: 'Réunion',
      continent: 'AF',
      prefixRegex: /^(FR|TO)[A-Z0-9/]*$/,
      flag: '🇫🇷',
    },
    {
      id: 454,
      name: 'Rwanda',
      continent: 'AF',
      prefixRegex: /^9X[A-Z0-9/]*$/,
      flag: '🇷🇼',
    },
    {
      id: 456,
      name: 'Senegal',
      continent: 'AF',
      prefixRegex: /^6[VW][A-Z0-9/]*$/,
      flag: '🇸🇳',
    },
    {
      id: 458,
      name: 'Sierra Leone',
      continent: 'AF',
      prefixRegex: /^9L[A-Z0-9/]*$/,
      flag: '🇸🇱',
    },
    {
      id: 460,
      name: 'Rotuma Island',
      continent: 'OC',
      prefixRegex: /^3D2[A-Z0-9/]*$/,
      flag: '🇫🇯',
    },
    {
      id: 462,
      name: 'South Africa',
      continent: 'AF',
      prefixRegex: /^Z[R-U][A-Z0-9/]*$/,
      flag: '🇿🇦',
    },
    {
      id: 464,
      name: 'Namibia',
      continent: 'AF',
      prefixRegex: /^V5[A-Z0-9/]*$/,
      flag: '🇳🇦',
    },
    {
      id: 466,
      name: 'Sudan',
      continent: 'AF',
      prefixRegex: /^ST[A-Z0-9/]*$/,
      flag: '🇸🇩',
    },
    {
      id: 468,
      name: 'Eswatini',
      continent: 'AF',
      prefixRegex: /^3DA[A-Z0-9/]*$/,
      flag: '🇸🇿',
    },
    {
      id: 470,
      name: 'Tanzania',
      continent: 'AF',
      prefixRegex: /^5[HI][A-Z0-9/]*$/,
      flag: '🇹🇿',
    },
    {
      id: 474,
      name: 'Tunisia',
      continent: 'AF',
      prefixRegex: /^3V[A-Z0-9/]*$/,
      flag: '🇹🇳',
    },
    {
      id: 478,
      name: 'Egypt',
      continent: 'AF',
      prefixRegex: /^SU[A-Z0-9/]*$/,
      flag: '🇪🇬',
    },
    {
      id: 480,
      name: 'Burkina Faso',
      continent: 'AF',
      prefixRegex: /^XT[A-Z0-9/]*$/,
      flag: '🇧🇫',
    },
    {
      id: 482,
      name: 'Zambia',
      continent: 'AF',
      prefixRegex: /^9[IJ][A-Z0-9/]*$/,
      flag: '🇿🇲',
    },
    {
      id: 483,
      name: 'Togo',
      continent: 'AF',
      prefixRegex: /^5V[A-Z0-9/]*$/,
      flag: '🇹🇬',
    },
    {
      id: 489,
      name: 'Conway Reef',
      continent: 'OC',
      prefixRegex: /^3D2[A-Z0-9/]*$/,
      flag: '🇫🇯',
    },
    {
      id: 490,
      name: 'Banaba',
      continent: 'OC',
      prefixRegex: /^T33[A-Z0-9/]*$/,
      flag: '🇰🇮',
    },
    {
      id: 492,
      name: 'Yemen',
      continent: 'AS',
      prefixRegex: /^7O[A-Z0-9/]*$/,
      flag: '🇾🇪',
    },
    {
      id: 497,
      name: 'Croatia',
      continent: 'EU',
      prefixRegex: /^9A[A-Z0-9/]*$/,
      flag: '🇭🇷',
    },
    {
      id: 499,
      name: 'Slovenia',
      continent: 'EU',
      prefixRegex: /^S5[A-Z0-9/]*$/,
      flag: '🇸🇮',
    },
    {
      id: 501,
      name: 'Bosnia-Herzegovina',
      continent: 'EU',
      prefixRegex: /^E7[A-Z0-9/]*$/,
      flag: '🇧🇦',
    },
    {
      id: 502,
      name: 'North Macedonia',
      continent: 'EU',
      prefixRegex: /^Z3[A-Z0-9/]*$/,
      flag: '🇲🇰',
    },
    {
      id: 503,
      name: 'Czech Republic',
      continent: 'EU',
      prefixRegex: /^O[KL][A-Z0-9/]*$/,
      flag: '🇨🇿',
    },
    {
      id: 504,
      name: 'Slovakia',
      continent: 'EU',
      prefixRegex: /^OM[A-Z0-9/]*$/,
      flag: '🇸🇰',
    },
    {
      id: 505,
      name: 'Pratas Island',
      continent: 'AS',
      prefixRegex: /^BV9P[A-Z0-9/]*$/,
      flag: '🇹🇼',
    },
    {
      id: 506,
      name: 'Scarborough Shoal',
      continent: 'AS',
      prefixRegex: /^BS7[A-Z0-9/]*$/,
      flag: '🇨🇳',
    },
    {
      id: 507,
      name: 'Temotu Province',
      continent: 'OC',
      prefixRegex: /^H40[A-Z0-9/]*$/,
      flag: '🇸🇧',
    },
    {
      id: 508,
      name: 'Austral Islands',
      continent: 'OC',
      prefixRegex: /^(FO|TO)[A-Z0-9/]*$/,
      flag: '🇵🇫',
    },
    {
      id: 509,
      name: 'Marquesas Islands',
      continent: 'OC',
      prefixRegex: /^(FO|TX)[A-Z0-9/]*$/,
      flag: '🇵🇫',
    },
    {
      id: 510,
      name: 'Palestine',
      continent: 'AS',
      prefixRegex: /^E4[A-Z0-9/]*$/,
      flag: '🇵🇸',
    },
    {
      id: 511,
      name: 'Timor-Leste',
      continent: 'OC',
      prefixRegex: /^4W[A-Z0-9/]*$/,
      flag: '🇹🇱',
    },
    {
      id: 512,
      name: 'Chesterfield Islands',
      continent: 'OC',
      prefixRegex: /^(FK|TX)[A-Z0-9/]*$/,
      flag: '🇳🇨',
    },
    {
      id: 513,
      name: 'Ducie Island',
      continent: 'OC',
      prefixRegex: /^VP6[A-Z0-9/]*$/,
      flag: '🇵🇳',
    },
    {
      id: 514,
      name: 'Montenegro',
      continent: 'EU',
      prefixRegex: /^4O[A-Z0-9/]*$/,
      flag: '🇲🇪',
    },
    {
      id: 515,
      name: 'Swains Island',
      continent: 'OC',
      prefixRegex: /^KH8[A-Z0-9/]*$/,
      flag: '🇦🇸',
    },
    {
      id: 516,
      name: 'Saint Barthélemy',
      continent: 'NA',
      prefixRegex: /^(FJ|TO)[A-Z0-9/]*$/,
      flag: '🇫🇷',
    },
    {
      id: 517,
      name: 'Curaçao',
      continent: 'SA',
      prefixRegex: /^PJ2[A-Z0-9/]*$/,
      flag: '🇨🇼',
    },
    {
      id: 518,
      name: 'Sint Maarten',
      continent: 'NA',
      prefixRegex: /^PJ7[A-Z0-9/]*$/,
      flag: '🇸🇽',
    },
    {
      id: 519,
      name: 'Saba and Sint Eustatius',
      continent: 'NA',
      prefixRegex: /^PJ[56][A-Z0-9/]*$/,
      flag: '🇧🇶',
    },
    {
      id: 520,
      name: 'Bonaire',
      continent: 'SA',
      prefixRegex: /^PJ4[A-Z0-9/]*$/,
      flag: '🇧🇶',
    },
    {
      id: 521,
      name: 'South Sudan',
      continent: 'AF',
      prefixRegex: /^Z8[A-Z0-9/]*$/,
      flag: '🇸🇸',
    },
    {
      id: 522,
      name: 'Kosovo',
      continent: 'EU',
      prefixRegex: /^Z6[A-Z0-9/]*$/,
      flag: '🇽🇰',
    },
  ];

  public static getAll(): DxccEntity[] {
    return this.dxcc;
  }

  public static getNames(): string[] {
    return this.dxcc.map((e) => e.name).sort();
  }

  public static getById(id: number): DxccEntity {
    return this.dxcc.find((rec) => rec.id === id);
  }

  public static getByName(name: string): DxccEntity {
    if (!name) {
      return null;
    }
    return this.dxcc.find((rec) => rec.name === name);
  }

  public static entitiesForCallsign(call: string): DxccEntity[] {
    return this.dxcc.filter(
      (rec) => rec.prefixRegex && rec.prefixRegex.test(call),
    );
  }
}
