name: "{Reusable} Deploy Web"
on:
  workflow_call:
    secrets:
      FIREBASE_TOKEN:
        required: true

defaults:
  run:
    working-directory: web

jobs:
  test:
    uses: k0swe/forester/.github/workflows/test-web.yml@main

  firebase-deploy-hosting:
    name: Deploy to Firebase Hosting
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: "22"

      - name: Setup Firebase CLI
        run: npm i -g firebase-tools

      - name: Read cached build artifacts
        id: read-cache
        uses: actions/cache@v4
        env:
          cache-name: cache-web-build-artifacts
        with:
          path: web/dist/
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}

      - name: Deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: npx firebase deploy --project k0swe-kellog --only hosting --token "$FIREBASE_TOKEN"
