name: "{Reusable} Deploy Javascript Functions"
on:
  workflow_call:
    secrets:
      FIREBASE_TOKEN:
        required: true

defaults:
  run:
    working-directory: functions/js-func/

jobs:
  test-js:
    uses: k0swe/forester/.github/workflows/test-func-js.yml@main

  deploy-javascript:
    runs-on: ubuntu-latest
    name: Deploy Javascript Functions to Cloud Functions
    needs: test-js

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v5
        with:
          # https://cloud.google.com/functions/docs/runtime-support#node.js
          node-version: "22"

      - name: Setup Firebase CLI
        run: npm i -g firebase-tools

      - name: Cache node deps
        uses: actions/cache@v4
        env:
          cache-name: cache-jsfunc-node-deps
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('functions/js-func/package-lock.json') }}

      - name: Install deps
        run: npm install

      - name: Deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: npx firebase deploy --project k0swe-kellog --only functions --token "$FIREBASE_TOKEN"
