name: "{Reusable} Test Javascript Functions"
on: workflow_call

defaults:
  run:
    working-directory: functions/js-func/

jobs:
  test-js:
    name: Build and test Javascript functions
    runs-on: ubuntu-latest

    steps:
      - name: Cache node deps
        uses: actions/cache@v4
        env:
          cache-name: cache-jsfunc-node-deps
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('functions/js-func/package-lock.json') }}

      - name: Install node
        uses: actions/setup-node@v5
        with:
          node-version: "24"

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Test
        run: |
          npm ci
          npm run build
