name: Test and Compile

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-firestore:
    uses: k0swe/forester/.github/workflows/test-firestore.yml@main

  test-func-go:
    uses: k0swe/forester/.github/workflows/test-func-js.yml@main

  test-func-js:
    uses: k0swe/forester/.github/workflows/test-func-go.yml@main

  test-web:
    uses: k0swe/forester/.github/workflows/test-web.yml@main
