name: Test and Compile

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-web:
    uses: k0swe/forester/.github/workflows/web-test-shared.yml@main

  test-firestore:
    uses: k0swe/forester/.github/workflows/firestore-test-shared.yml@main
