name: "{Reusable} Test Golang Functions"
on: workflow_call

defaults:
  run:
    working-directory: functions/go-func/

jobs:
  test-go:
    name: Build and test Golang functions
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          # https://cloud.google.com/functions/docs/runtime-support#go
          go-version: 1.24.x

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: make build
