name: "{Reusable} Update Javascript Function dependencies"
on:
  workflow_call:
    secrets:
      GH_PAT:
        required: true

defaults:
  run:
    working-directory: functions/js-func/

jobs:
  update-js-func:
    name: Update Javascript Function dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          # https://cloud.google.com/functions/docs/runtime-support#node.js
          node-version: "24"

      - name: Checkout code
        uses: actions/checkout@v5

      - name: npm update
        run: |
          npx npm-check-updates -u -x eslint,firebase-admin,typescript
          npm install -f
          npm update
          npm install

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: "${{ secrets.GH_PAT }}"
          add-paths: "functions/js-func/package*.json"
          commit-message: npm update (js-func)
          title: npm update (js-func)
          branch: update-js-func
          author: "github-actions <github-actions@github.com>"
