name: npm update
on: workflow_dispatch

jobs:
  npm-update:
    name: npm update
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node deps
        uses: actions/cache@v3
        env:
          cache-name: cache-node-deps
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: npm update
        run: |
          npm install
          npm update
          npm install

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: '${{ secrets.GH_PAT }}'
          add-paths: 'package*.json'
          commit-message: npm update
          title: npm update
          branch: npm-update
          author: 'github-actions <github-actions@github.com>'
