name: "{Reusable} Update Web license report"
on:
  workflow_call:
    secrets:
      GH_PAT:
        required: true

defaults:
  run:
    working-directory: web

jobs:
  update-web-license:
    name: Update Web license report
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Cache node deps
        uses: actions/cache@v4
        env:
          cache-name: cache-web-node-deps
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('web/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Update license report
        run: npm run license-report

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: "${{ secrets.GH_PAT }}"
          add-paths: "web/src/assets/license-report.json"
          commit-message: Update web license report
          title: Update web license report
          branch: update-web-license
          author: "github-actions <github-actions@github.com>"