name: Deploy Web

on: workflow_dispatch

defaults:
  run:
    working-directory: web

jobs:
  test:
    uses: k0swe/forester/.github/workflows/web-test-shared.yml@main

  firebase-deploy:
    name: Deploy to Firebase Hosting
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read cached build artifacts
        id: read-cache
        uses: actions/cache@v3
        env:
          cache-name: cache-web-build-artifacts
        with:
          path: web/dist/
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Tag as deployed
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git tag deployed --force
          git push --tags --force

      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@v1
        with:
          name: Forester Deploy
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
        if: always()
